export const ACTION_TYPES = {
  WORKFLOW_LOGS_REQUEST_STARTED:
    "/kestraa/workflow/WORKFLOW_LOGS_REQUEST_STARTED",
  WORKFLOW_LOGS_REQUEST_FINISHED:
    "/kestraa/workflow/WORKFLOW_LOGS_REQUEST_FINISHED",
  FETCH_WORKFLOW_LOGS: "/kestraa/workflow/FETCH_WORKFLOW_LOGS",
  SAVE_WORKFLOW_LOG: "/kestraa/workflow/SAVE_WORKFLOW_LOG",
  SET_WORKFLOW_LOGS: "/kestraa/workflow/SET_WORKFLOW_LOGS",
  SET_LAST_WORKFLOW_LOG: "/kestraa/workflow/SET_LAST_WORKFLOW_LOG",
  CLEAR_WORKFLOW_LOGS: "/kestraa/workflow/CLEAR_WORKFLOW_LOGS",
  SET_ERROR: "/kestraa/workflow/SET_ERROR"
};
